// lib/data/database.dart — User Memory Database (Drift/SQLite)
//
// Stores persistent user facts, preferences, and memories.
// Injected into Gemini system instruction on each session connect.

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'dart:io';

part 'database.g.dart'; // Generated by drift_dev

/// User memory table
class UserMemories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get category => text()(); // preference, fact, schedule, contact, other
  TextColumn get key => text()(); // e.g., 'coffee_preference'
  TextColumn get value => text()(); // e.g., 'Prefers dark roast, no sugar'
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();

  @override
  List<Set<Column>> get uniqueKeys => [{category, key}];
}

/// Chat message history table
class ChatMessages extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get content => text()();
  BoolColumn get isUser => boolean()();
  BoolColumn get isSystem => boolean()();
  DateTimeColumn get timestamp => dateTime().withDefault(currentDateAndTime)();
}

/// Drift database for user memories and chat history
@DriftDatabase(tables: [UserMemories, ChatMessages])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  /// Upsert a memory (insert or update by category+key)
  Future<void> upsertMemory({
    required String category,
    required String key,
    required String value,
  }) async {
    await into(userMemories).insertOnConflictUpdate(
      UserMemoriesCompanion(
        category: Value(category),
        key: Value(key),
        value: Value(value),
        updatedAt: Value(DateTime.now()),
      ),
    );
  }

  /// Query memories by optional category and/or keyword
  Future<List<UserMemory>> queryMemories({
    String? category,
    String? keyword,
  }) async {
    if (category != null && keyword != null) {
      final keywordLower = '%${keyword.toLowerCase()}%';
      return (select(userMemories)
            ..where((tbl) =>
                tbl.category.equals(category) &
                (tbl.key.lower().like(keywordLower) |
                    tbl.value.lower().like(keywordLower))))
          .get();
    }

    if (category != null) {
      return (select(userMemories)
            ..where((tbl) => tbl.category.equals(category)))
          .get();
    }

    if (keyword != null) {
      final keywordLower = '%${keyword.toLowerCase()}%';
      return (select(userMemories)
            ..where((tbl) =>
                tbl.key.lower().like(keywordLower) |
                tbl.value.lower().like(keywordLower)))
          .get();
    }

    return select(userMemories).get();
  }

  /// Get all stored memories
  Future<List<UserMemory>> getAllMemories() async {
    return select(userMemories).get();
  }

  /// Delete a memory by category and key
  Future<int> deleteMemory(String category, String key) async {
    return (delete(userMemories)
          ..where((tbl) => tbl.category.equals(category) & tbl.key.equals(key)))
        .go();
  }

  /// Get memory count
  Future<int> get memoryCount async {
    final count = await userMemories.count().getSingle();
    return count;
  }

  // ── Chat Messages ──

  /// Save a chat message to history
  Future<void> saveMessage({
    required String content,
    required bool isUser,
    required bool isSystem,
    required DateTime timestamp,
  }) async {
    await into(chatMessages).insert(
      ChatMessagesCompanion(
        content: Value(content),
        isUser: Value(isUser),
        isSystem: Value(isSystem),
        timestamp: Value(timestamp),
      ),
    );
  }

  /// Load recent messages (most recent first, limited)
  Future<List<ChatMessage>> loadRecentMessages({int limit = 50}) async {
    return (select(chatMessages)
          ..orderBy([
            (t) => OrderingTerm(expression: t.timestamp, mode: OrderingMode.asc),
          ])
          ..limit(limit))
        .get();
  }

  /// Clear all chat history
  Future<void> clearHistory() async {
    await delete(chatMessages).go();
  }
}

/// Open a native SQLite database connection
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'user_memory.db'));
    return NativeDatabase.createInBackground(file);
  });
}
